# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c8619ee946c3d3a62125db05a27366e33fde1b87ac4bbd53dccdcd034c59c221e9e29bd5d98e5f15b0cec65b357b5554eccf1279b1143ac2325602449b4241

test:
  secret_key_base: b7bfdf9b8b13ab5bee9e7484dffa1fde838c1f46461317a3ab72890ce04507695a9f93d3bd842a585c4ceca74364d09b54ba5aef755f2cf8eba356888a7968d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
